# Generated by Django 6.0.4 on 2026-04-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('NGN', 'Nigerian Naira'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='NGN', max_length=3),
        ),
        migrations.AddField(
            model_name='stock',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('NGN', 'Nigerian Naira'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='NGN', max_length=3),
        ),
    ]
