# Generated by Django 6.0.4 on 2026-05-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_asset_currency_stock_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='currency',
        ),
        migrations.AddField(
            model_name='asset',
            name='sale_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='sale_converted_to_cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stock',
            name='sale_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('real_estate', 'Real Estate'), ('vehicle', 'Vehicle'), ('land', 'Land'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cashaccount',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('NGN', 'Nigerian Naira'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='NGN', max_length=3),
        ),
    ]
