# Generated by Django 6.0.4 on 2026-05-09 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_stock_currency_asset_sale_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('NGN', 'Nigerian Naira')], default='NGN', max_length=3),
        ),
        migrations.AlterField(
            model_name='cashaccount',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('NGN', 'Nigerian Naira')], default='NGN', max_length=3),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('NGN', 'Nigerian Naira')], default='NGN', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
