# Generated by Django 6.0.4 on 2026-05-09 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_asset_currency_alter_cashaccount_currency_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
